In [1]:
import pandas as pd

## Reading Data

In [2]:
df=pd.read_csv("Data.csv")

In [3]:
df.head()

        Fever  BodyPain  Age  RunnyNose  DiffBreath  InfectionProb
0  101.242423         1   67          1           0              1
1   98.687390         0   28          0           0              0
2   99.085007         1   36          0          -1              0
3  100.056629         0   39          0           1              0
4  101.254028         0   28          1          -1              1

In [4]:
df.tail()

           Fever  BodyPain  Age  RunnyNose  DiffBreath  InfectionProb
2494   98.555095         0   41          1          -1              1
2495  100.645745         0   65          0           1              0
2496  100.716848         1   75          1           1              0
2497  100.303598         0   54          1           0              0
2498  101.801661         1   95          1           1              0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2499 entries, 0 to 2498
Data columns (total 6 columns):
Fever            2499 non-null float64
BodyPain         2499 non-null int64
Age              2499 non-null int64
RunnyNose        2499 non-null int64
DiffBreath       2499 non-null int64
InfectionProb    2499 non-null int64
dtypes: float64(1), int64(5)
memory usage: 117.2 KB

In [6]:
df['DiffBreath'].value_counts()

 0    839
 1    833
-1    827
Name: DiffBreath, dtype: int64

In [7]:
df.describe()

,Fever,BodyPain,Age,RunnyNose,DiffBreath,InfectionProb
count,2499.000000,2499.000000,2499.000000,2499.000000,2499.000000,2499.000000
mean,100.003656,0.489396,50.112045,0.520208,0.002401,0.503401
std,1.132069,0.499988,28.949188,0.499691,0.815185,0.500088
min,98.000222,0.000000,1.000000,0.000000,-1.000000,0.000000
25%,99.042992,0.000000,26.000000,0.000000,-1.000000,0.000000
50%,99.990855,0.000000,49.000000,1.000000,0.000000,1.000000
75%,100.978242,1.000000,75.000000,1.000000,1.000000,1.000000
max,101.997446,1.000000,100.000000,1.000000,1.000000,1.000000

# TRAIN TEST SPLITTING

In [8]:
import numpy as np

In [9]:
def data_split(data,ratio):
    np.random.seed(42)
    shuffled=np.random.permutation(len(data))
    test_set_size=int(len(data)*ratio)
    test_indices=shuffled[:test_set_size]
    train_indices=shuffled[test_set_size:]
    return data.iloc[train_indices],data.iloc[test_indices]

In [10]:
train,test=data_split(df,0.3)

In [11]:
train

           Fever  BodyPain  Age  RunnyNose  DiffBreath  InfectionProb
2121  100.177815         0   37          0           1              0
1779   99.802761         0   33          1           0              0
115    98.059871         0   14          0          -1              0
940    99.795153         0   81          1           1              0
744   100.149227         0   53          1           0              1
...          ...       ...  ...        ...         ...            ...
1638  100.581469         0   90          1           1              0
1095  100.191678         1   10          1           1              1
1130   98.437565         0   11          1          -1              0
1294   99.819747         0   67          1           0              0
860    98.699916         1   42          1          -1              1

[1750 rows x 6 columns]

In [12]:
test

           Fever  BodyPain  Age  RunnyNose  DiffBreath  InfectionProb
2319  101.444737         0   42          0          -1              1
1865   98.609798         0    6          0           0              1
902    99.270095         0    8          0          -1              0
2240  100.079650         0   52          1           1              0
1285  101.397135         1    7          1           1              1
...          ...       ...  ...        ...         ...            ...
121    99.783702         0   90          1           0              1
2194  100.787006         0  100          0           0              1
1550   99.663525         1   11          1           1              0
1901   98.108836         0    6          1           0              0
2263   99.182244         0   60          1           1              1

[749 rows x 6 columns]

In [13]:
X_train=train[['Fever','BodyPain','Age','RunnyNose','DiffBreath']].to_numpy()
X_test=test[['Fever','BodyPain','RunnyNose','DiffBreath']].to_numpy()
Y_train=train[['InfectionProb']].to_numpy().reshape(1750,)
Y_test=test[['InfectionProb']].to_numpy().reshape(749,)

In [14]:
X_train

array([[100.177815  ,   0.        ,  37.        ,   0.        ,
          1.        ],
       [ 99.80276057,   0.        ,  33.        ,   1.        ,
          0.        ],
       [ 98.05987129,   0.        ,  14.        ,   0.        ,
         -1.        ],
       ...,
       [ 98.43756545,   0.        ,  11.        ,   1.        ,
         -1.        ],
       [ 99.81974744,   0.        ,  67.        ,   1.        ,
          0.        ],
       [ 98.69991643,   1.        ,  42.        ,   1.        ,
         -1.        ]])

In [15]:
X_test

array([[101.4447371 ,   0.        ,   0.        ,  -1.        ],
       [ 98.60979834,   0.        ,   0.        ,   0.        ],
       [ 99.27009456,   0.        ,   0.        ,  -1.        ],
       ...,
       [ 99.66352537,   1.        ,   1.        ,   1.        ],
       [ 98.10883556,   0.        ,   1.        ,   0.        ],
       [ 99.18224413,   0.        ,   1.        ,   1.        ]])

In [16]:
Y_train

array([0, 0, 0, ..., 0, 0, 1], dtype=int64)

In [17]:
Y_test

array([1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1], dtype=int64)

In [18]:
from sklearn.linear_model import LogisticRegression

In [19]:
clf=LogisticRegression()
clf.fit(X_train,Y_train)

c:\users\dell\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [20]:
inputFeatures=[100,1,22,1,1]
infProb=clf.predict_proba([inputFeatures])[0][1]

In [21]:
infProb

0.5036829618860789